# This is a basic workflow to showcase the use of Reusable Workflows

name: reusable

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: umangcypher-BH/pancake/.github/workflows/main.yml@master
    with:
      image_name: umangcypherbh/trivyscan
      tag: $GITHUB_RUN_NUMBER
    secrets:
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}
