# This is a basic workflow to showcase the use of Reusable Workflows

name: reusable

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: umangcypher-BH/pancake/.github/workflows/reusable.yaml@master  
     
    with:
     image_name: trivyscan
     tag: umangcypherbh/trivyscan
    secrets:
      username: ${{secrets.DOCKER_HUB_USERNAME}}
      password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
